### ISSUE TITLE
Update contract app

### ISSUE THREAD

**Issue by wesolan** [wesolan/BondAbility#22]
Need to put Lex's signature page on the bottom of the contract app. We'll need to adjust the wording in the IA wherever it states "Lexington" to read "the Surety".

**Comment by bcarola115** [comment]
Drew liv can not unlock this. you need to so she can make the change

**Comment by wesolan** [comment]
Unlocked full Lex Contract Express App and emailed to Liv and CC Brie. Liv can now manipulate the app.

**Comment by oorndorff** [comment]
Replaced. Able to view new app w/sig page on website
