### ISSUE TITLE
Gather all digital seals and POAs for our companies

### ISSUE THREAD

**Issue by wesolan** [wesolan/BondAbility#5]
Folder is already in D-link. Brie will then need to upload those once complete.

**Comment by oorndorff** [comment]
I have saved to DLink POAs & seals for CBIC, RLI, Skyward, Merchants, NGM, Platte, Sompo, Lexington, and ASC.

I only have the Lib POA for now. The seal is coming per Alistair.

I have a seal for SureTec but no POA. Per Scotta, "Powers are either paper ones that we have sent out, electronic ones that you get from SQ or an electronic one we send for a specific situation.  Both electronic versions are bond specific.   We don’t typically send out an electronic POA that can be used for all bonds."

Hudson is getting approval for the seal/POA.

Do either of you have a POA or seal for Capitol? Are we worried about obtaining POAs/seal for Hartford, IFIC, PNAT?

**Comment by wesolan** [comment]
Not worried about the seals for  Hartford, IFIC, PNAT. POA and seal for Capitol is in the "Capitol" folder in Dlink. Move them over to your electronic sigs and poas. Keep updated with this so it's finished ASAP.

**Comment by oorndorff** [comment]
I have Hudson seal now, per Nancy "The POA prints out of the system when the bond is purchased."

I moved over the Capitol POA/Seal

I also have my sig & notary seal, Drew's sig & Brie's sig saved.

In Brie's admin Git Hub to move forward
