### ISSUE TITLE
City of Germantown, TN ROW II page needed

### ISSUE THREAD

**Issue by oorndorff** [wesolan/BondAbility#86]
II w/Merch

$15k bond
$150 prem - can do multiyear!
Also can email bond

Just need name, address, effective date, county

Merch link: https://secure2.merchantsbonding.com/obligations/114429?instant_price_button=1

BF states: Bond for Work In or Upon City Streets, Alleys, Public Places, or Ways

**Comment by wesolan** [comment]
Created.
